---

name: 'MKDocs'

on:
  workflow_dispatch: {}

  push:
    branches:
      - 'master'


jobs:


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:


      - name: Checkout Code
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true


      - name: MkDocs Docker CI
        shell: bash
        env:
          IS_BUILD: 1
        run: |
          git submodule update --init

          docker run -t --rm \
            -e IS_BUILD=1 \
            -e MKDOCS_SRC_DIRECTORY=pages \
            -e token=${{ secrets.ACTIONS_TOKEN_RO }} \
            -e template_repo='http://${token}@gitea-http.git.svc:3000/infrastructure/website-template.git' \
            --mount type=volume,source=${JOB_CONTAINER_NAME},target=${GITHUB_WORKSPACE} \
            --workdir ${GITHUB_WORKSPACE} \
            harbor.earth.nww/docker/nofusscomputing/mkdocs-ci:0.4.1 \


      - name: Upload Artifacts
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: artifacts
          path: artifacts/


  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:


      - name: Download Artifacts
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/Download-artifact@v3
        if: success() || failure()
        with:
          name: artifacts
          # path: artifacts/


      - name: Copy files to Webserver
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/ssh-scp-deploy@v1.2.0
        with:
          local: 'pages/*'
          remote: '/opt/webserver/nofusscomputing.com/'
          host: ${{ secrets.WEBSERVER_HOST }}
          user: ${{ secrets.WEBSERVER_SSH_USERNAME }}
          password: ${{ secrets.WEBSERVER_SSH_PASSWORD }}
          pre_upload: rm -rf /opt/webserver/nofusscomputing.com/*
          post_upload: ls -la /opt/webserver/nofusscomputing.com/
          scp_options: -v
