---

name: 'Release'


on:
  push:
    tags:
      - '*'


env:
  # ACTIONS_RUNNER_DEBUG: "true"
  # ACTIONS_STEP_DEBUG: "true"
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}


jobs:


  create:
    name: 'Create'
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:


      - name: Trace
        shell: bash
        run: |
          export


      - name: Install Commitizen
        shell: bash
        run: |
          pip install \
            commitizen==3.28.0


      - name: Checkout Code
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: ${{ github.ref_name }}


      - name: Create Incremental Changelog
        shell: bash
        run: |
          export PREV_GIT_TAG="$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`)";
          export CURR_GIT_TAG="${{ github.ref_name }}";

          cz changelog --dry-run --merge-prerelease --unreleased-version "$PREV_GIT_TAG" "$CURR_GIT_TAG" > changelog-release.md;


      - name: Gitea Release
        uses: http://${{ secrets.ACTIONS_TOKEN_RO }}@gitea-http.git.svc:3000/actions/gitea-release-action@v1.3.5
        with:
          body_path: changelog-release.md
          name: ${{ github.ref_name }}
          draft: true
